version: 1.2

workflows:

   -  name: workflowA
      publish: true
      subclass: CWL
      primaryDescriptorPath: /workflow.cwl
      testParameterFiles:
        - /empty.json
      authors:
        - name: Foo Bar
          email: sdfklfjksdl

   -  name: workflowB
      publish: true
      subclass: CWL
      primaryDescriptorPath: /workflow.cwl
      testParameterFiles:
        - /empty.json

tools:

   -  name: toolA
      publish: true
      subclass: CWL
      primaryDescriptorPath: /tool.cwl
      testParameterFiles:
        - /empty.json
      authors:
        - name: Bacon Bits
          email: test@test.com

   -  name: toolB
      publish: true
      subclass: CWL
      primaryDescriptorPath: /tool.cwl
      testParameterFiles:
        - /empty.json
